### ISSUE TITLE
entities.GroupChat missing funcitonality

### ISSUE THREAD

**Issue by brendenmcfarlane** [CSC207-2022F-UofT/course-project-fixthewifi#32]
.addMsg() and deleteMsg() not completed.
should also add the rep. invar. that the first element in GroupChat.members is the admin, then update the methods to abide by this.

**Comment by brendenmcfarlane** [comment]
the representation invariant was updated in another PR that needed it.

**Comment by xingjianll** [comment]
Is this done?
