### ISSUE TITLE
[Magic Number] 4396

### ISSUE THREAD

**Issue by brendenmcfarlane** [CSC207-2022F-UofT/course-project-fixthewifi#68]
We are all using the peerPort number 4396 on client side Controllers, this is ineffective if we decide to change the port. We should either discuss a way to remove this hardcoded value, or do one of these ideas:
- Create a constant on the client side to store this value
- set a default value within the comManager

the classes that will need to be changed:
- all client side controllers
- client side comManager
- potentially more

**Comment by xingjianll** [comment]
Good point, dependency injection should solve this?

**Comment by xingjianll** [comment]
Solved.
